# Generated by Django 4.2 on 2025-08-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_sitesetting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='keyboardless_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='mouseless_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='phase',
            field=models.CharField(choices=[('mouseless', 'Mouseless'), ('keyboardless', 'Keyboardless')], default='mouseless', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='question_type',
            field=models.CharField(choices=[('mouseless', 'Mouseless Challenge'), ('keyboardless', 'Keyboardless Challenge')], default='mouseless', max_length=20),
        ),
    ]
