# Generated by Django 4.2 on 2025-08-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_card_keyboardless_score_card_mouseless_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='document',
            field=models.FileField(blank=True, help_text='Upload reference document for participants', null=True, upload_to='task_documents/'),
        ),
    ]
