# Generated by Django 4.2 on 2025-08-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0015_task_document"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["points", "order"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="hint",
            field=models.CharField(default="No hint!!", max_length=1000),
        ),
    ]
