# Generated by Django 4.2 on 2026-07-22 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0016_alter_task_options_alter_task_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bomb_duration',
            field=models.PositiveIntegerField(default=60, help_text='Time bomb countdown duration in seconds (only used if "Has time bomb" is enabled)'),
        ),
        migrations.AddField(
            model_name='task',
            name='has_time_bomb',
            field=models.BooleanField(default=False, help_text='Enable a ticking time-bomb countdown for this question. If the timer runs out before the participant solves it, the question is forfeited (no penalty, they just miss out on the points).'),
        ),
        migrations.CreateModel(
            name='BombForfeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_forfeited', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bomb_forfeits', to='quiz.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'task')},
            },
        ),
    ]
