# Generated by Django 4.2 on 2026-07-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_task_bomb_duration_task_has_time_bomb_bombforfeit'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='bomb_started_at',
            field=models.DateTimeField(blank=True, help_text='When the time bomb was first activated for this user on this question', null=True),
        ),
    ]
